### ISSUE TITLE
[Stonecutter GUI Remastered] - Compatibility with Vanilla Tweaks' Dark GUI

### ISSUE THREAD

**Issue by kkellogg378** [A5ho9999/MinecraftMods#10]
Title relatively self-explanatory. I've gone ahead and redesigned the texture in the exact style of the Dark GUI resource pack from Vanilla Tweaks, I just couldn't figure out how to make a resource pack that utilized it.

![larger_stonecutter_screen](https://github.com/A5ho9999/MinecraftMods/assets/32850733/00309206-1b99-4e2b-987d-30e0c999ffa6)

**Comment by A5ho9999** [comment]
Thanks, I had planned to include a resource pack that gave a dark GUI so this is very useful. 

For a resource pack, the image path is `assets/stonecutter-remastered/textures/gui/larger_stonecutter_screen.png`

**Comment by A5ho9999** [comment]
A resource pack has been added to v1.1.1 when the mod is installed.
