### ISSUE TITLE
[Totem Party Popper] - Disable custom item

### ISSUE THREAD

**Issue by Daniel99j2** [A5ho9999/MinecraftMods#12]
**Is your feature request. Please describe.**
Hey, in the config, there is an option to change the visual item in the animation. The issue/request is a toggle for if it will override the item. This is useful for people who may have custom model data totems and want them to show the custom model in the animation

**Additional context**
A shadow totem custom model (CustomModelData) that is being popped:
As you can see, the totem I was holding was dark gray, but the animation is yellow
![2024-06-03_15 32 09](https://github.com/A5ho9999/MinecraftMods/assets/121533735/be610de6-75c8-47f2-9897-09c2d61ec84c)

**Comment by A5ho9999** [comment]
New versions have been released on Modrinth to address this, a fix as been added to display the totem correctly if not changed in the Configuration as well as an extra option added to quickly enable and disable it.

https://modrinth.com/mod/totem-party-popper/versions
