### ISSUE TITLE
[Brrrrock+ (Yeeterite Extras)] - Mined Blocks with Yeeterite Hammer only results in Player Stats showing only 1 block mined instead the amount of blocks actually mined with set dig space size

### ISSUE THREAD

**Issue by BabyD252** [A5ho9999/MinecraftMods#14]
**Mod name**:  Brrrrock+ (Yeeterite Extras)
**Mod Version**:  v1.0.3-1.20+
**Fabric Version/Loader**: 0.92.1 / 0.15.11
**Minecraft Version**: 1.20.1

**Describe the bug**
When using the Yeeterite Hammer and say you set to a dig space of 5 x 5 Mining blocks results in only 1 block showing mined in the player stats.

**To Reproduce**
Check your player stats before using the Yetterite Hammer how many blocks that is shows mined then go mine more of that block any dig size it will result in the stats only going up 1 block mined

**Expected behavior**
It should advance the player stats to how every many blocks were mined.

**Screenshots**
These screenshots are submitted from a  member of my community SMP He mined stone it only advanced one block of stone mined. I have the before stats, the sized mined, and the after stats. 

![2024-06-18_18 42 22](https://github.com/A5ho9999/MinecraftMods/assets/152373355/6ceb9633-c8f9-43c9-8596-ece181b13946)
![2024-06-18_18 42 42](https://github.com/A5ho9999/MinecraftMods/assets/152373355/e60c04d5-5047-4167-8801-eb36fec239e1)
![2024-06-18_18 42 57](https://github.com/A5ho9999/MinecraftMods/assets/152373355/efd963a8-9cf3-42ce-890a-b629ab75d4ce)

**Comment by A5ho9999** [comment]
Thanks for the report. Should be fixed in [v1.1.1](https://modrinth.com/mod/yeeterite-extras/version/1.1.1-1.20). This will most likely be the last update for 1.20 versions aside from any major bugs.
