### ISSUE TITLE
Crash on Startup

### ISSUE THREAD

**Issue by darkequine** [A5ho9999/MinecraftMods#19]
### Mod name

Stacks Are Stacks

### Mod Version

1.0.0

### Minecraft Version

1.21

### Fabric Versions

Fabric Loader: 0.16.3 Fabric API: 0.102.0

### Confirmation Checkboxes

- [X] I have checked the Supported Versions and confirmed this version is still supported
- [X] I have confirmed that this issue can be reproduced with minimal setup (Not a large Modpack)
- [X] I am NOT using a 3rd Party Client (Feather Client, Luna Client, etc)

### Issue Description

Crash on startup with Stacks Are Stacks installed.

### Crash Report / Log

https://pastebin.com/fCTXKJp5

**Comment by A5ho9999** [comment]
This should be fixed in the latest version of [Yeeterite](https://modrinth.com/mod/yeeterite/version/3.0.1-1.21.0)
