### ISSUE TITLE
Superflat Plus crash with Puzzles Lib

### ISSUE THREAD

**Issue by Makerman991** [A5ho9999/MinecraftMods#20]
### Mod name

Other

### Mod Version

SuperflatPlus v1.4.0

### Minecraft Version

1.21.0

### Fabric Versions

Fabric Loader: 0.16.5-1.21 | API: 0.102.0+1.21

### Confirmation Checkboxes

- [X] I have checked the Supported Versions and confirmed this version is still supported
- [X] I have confirmed that this issue can be reproduced with minimal setup (Not a large Modpack)
- [X] I am NOT using a 3rd Party Client (Feather Client, Luna Client, etc)

### Issue Description

Having Puzzle Lib and it's dependancies with Superflat Plus and its dependency (owo-lib, not including mod menu) will stop the game from launching entirely.

### Steps to reproduce

1. Download puzzle lib and superflat plus (With dependancies)
2. Launch game
3. Experience crash

### Expected Behavior

Game should launch.

### Crash Report / Log

https://gist.github.com/Makerman991/b32f5f9100c6145b883d886a5c9e47f4

**Comment by A5ho9999** [comment]
Yes this is a known conflict, Puzzle Lib is modifying the Parrot Entity Interaction (without good reason) which conflicts with the breeding Parrots feature. Unfortunately due to this you will have to remove it and avoid using any mods that require it in order to use the Superflat mod.
