### ISSUE TITLE
Elytra dupe

### ISSUE THREAD

**Issue by cocarroll** [A5ho9999/MinecraftMods#23]
### Mod name

Stacks Are Stacks

### Mod Version

1.0.1

### Minecraft Version

1.21.2

### Fabric Versions

1.21.3

### Confirmation Checkboxes

- [X] I have checked the Supported Versions and confirmed this version is still supported
- [X] I have confirmed that this issue can be reproduced with minimal setup (Not a large Modpack)
- [X] I am NOT using a 3rd Party Client (Feather Client, Luna Client, etc)

### Issue Description

Dupe when using anvil

### Steps to reproduce

Take enchanting book out of bundle
Add this item to an elytra in an anvil
Your elytra stays in the anvil and you get whatever added enchant as well

**Comment by cocarroll** [comment]
Id love to help any way I can

**Comment by A5ho9999** [comment]
This should be fixed in [v1.0.2](https://modrinth.com/mod/stacks-are-stacks/version/1.0.2-1.21.2). Thanks for the report.
