### ISSUE TITLE
[Mod] - Issue

### ISSUE THREAD

**Issue by TheLucXas** [A5ho9999/MinecraftMods#3]
**Mod name**:Hopper The Hedgehog
**Mod Version**:v1.3.0-1.20.2
**Fabric Version/Loader**:0.14.22
**Minecraft Version**:1.20.1

**Describe the bug**
When using the Gloppers! mod all the slots except the second hopper slot do not work, it does not transfer the items just stay there, for example if you throw a stack of any item in the hopper it will not transfer it to another hopper or to a chest or anything, but if you throw another stack it will start transferring only the second slot, if you throw more stacks the other slots will be paused and only the second slot will be transferred.

**To Reproduce**
just using the hoppers, you don't even need to use the Gloppers mod! as such, having it installed already causes the error

**Expected behavior**
All the hopper slots should work, since it is not necessary to use the Gloppers! mod functionalities for the error to happen, even without touching the Hopper The Hedgehog mod speeds.

**Screenshots**
I attach a video

https://github.com/A5ho9999/MinecraftMods/assets/36708279/fc5fddc2-941e-44f2-971c-13c7a0cf0b96

**Comment by A5ho9999** [comment]
Thanks for the report, I didn't encounter this issue but I'll be sure to check. Could you please also provide a list of all the mods you are using in-case it's a conflict related issue.

**Comment by A5ho9999** [comment]
Oh sorry, I misread. I believe this issue may be more related to Gloppers as they override more hopper functions where as this mod only adjusts vanilla numbers. I will still keep this open in-case I work something out

**Comment by TheLucXas** [comment]
Ok no problem, thanks

**Comment by TheLucXas** [comment]
here is a screenshot of the mods list
![image](https://github.com/A5ho9999/MinecraftMods/assets/36708279/ec610d9c-056d-4521-a6ec-9caee05d67df)
![image](https://github.com/A5ho9999/MinecraftMods/assets/36708279/7606e0cd-621b-4319-a164-a3a7d0e92a89)
![image](https://github.com/A5ho9999/MinecraftMods/assets/36708279/92d99a4e-54f1-489a-85b0-77e92e777ee4)
![image](https://github.com/A5ho9999/MinecraftMods/assets/36708279/b3ba980d-464b-4221-9742-6e2920e1a4f7)

**Comment by A5ho9999** [comment]
Thanks, I will attempt to look into this over the coming days. Can you also just confirm the version you are using as you provided v1.3.0-1.20.2 but the screenshots list v1.2.0-1.20

**Comment by TheLucXas** [comment]
> Thanks, I will attempt to look into this over the coming days. Can you also just confirm the version you are using as you provided v1.3.0-1.20.2 but the screenshots list v1.2.0-1.20

Yes sorry I forgot to clarify that I am using the mod on a server, the list of mods that I sent you is the same as the server, but on the server the mod is updated.
![image](https://github.com/A5ho9999/MinecraftMods/assets/36708279/bd8229f8-c7d8-4a54-b84b-53c645962b4e)

**Comment by A5ho9999** [comment]
I was unable to recreate this on a server with any mods on the list that I suspect would create the issue. If possible could you please provide a version/export of the modpack so I can check it out fully.

**Comment by TheLucXas** [comment]
sorry I did not receive a notification of the message and could not read it, here is the link to the mods:
https://www.mediafire.com/file/43mu3gsfxeoz9hb/mods.rar/file

**Comment by A5ho9999** [comment]
Sorry for the delay, but I tested with all these mods and didn't encounter this issue on a server
