### ISSUE TITLE
[Glass Carpet] - Tinted Glass Carpet and Tinted Glass Pane doesnt stop light

### ISSUE THREAD

**Issue by peow** [A5ho9999/MinecraftMods#5]
**Mod name**: Glass Carpet
**Mod Version**: v1.1.0-1-20
**Fabric Version/Loader**: Fabric Loader 0.14.22
**Minecraft Version**: Fabric 1.20.1

**Describe the bug**
Tinted Glass Carpet and Tinted Glass Pane doesnt stop light

**Screenshots**
with Tinted Glass Carpet:

![2024-01-27_13 28 40](https://github.com/A5ho9999/MinecraftMods/assets/105888751/9c34830a-6b5e-40bd-9933-4e054e99c900)

with normal Tinted Glass Block:

![2024-01-27_13 30 42](https://github.com/A5ho9999/MinecraftMods/assets/105888751/3aa75d6a-5acc-452f-b4a6-1e3d583f5f86)

the same also happens with Tinted Glass Pane

![2024-01-27_13 32 40](https://github.com/A5ho9999/MinecraftMods/assets/105888751/88c63a1e-9607-45e2-9b91-d5a477d0ef05)

----------
If it is possible to fix this, please publish an update for Fabric 1.20.1

**Comment by A5ho9999** [comment]
Thanks for the report, I'll look into it

**Comment by A5ho9999** [comment]
This has been fixed in v1.1.1, you can get it here: https://modrinth.com/mod/glass-carpet/version/1.1.1-1.20
