### ISSUE TITLE
[Glass Carpet] - Glass Carpets doesnt change beacon beam color

### ISSUE THREAD

**Issue by peow** [A5ho9999/MinecraftMods#6]
**Mod name**: Glass Carpet
**Mod Version**:  1.1.1
**Fabric Version/Loader**: Fabric v0.15.7
**Minecraft Version**: 1.20.1

**Describe the bug**
Glass Carpets doesnt change beacon beam color
![2024-03-25_18 37 37](https://github.com/A5ho9999/MinecraftMods/assets/105888751/b1398dd5-fa18-4a4b-9fe0-8a629c503762)

**Expected behavior**
Carpets change beam color

**Comment by A5ho9999** [comment]
Fixed in [v1.1.2](https://modrinth.com/mod/glass-carpet/version/gNQ6x7go). Thanks for the report.
