### ISSUE TITLE
[SpongeSucc] - Crash on Load

### ISSUE THREAD

**Issue by darkequine** [A5ho9999/MinecraftMods#7]
**Mod name**: SpongeSucc
**Mod Version**:  2.0.0-1.20+
**Fabric Version/Loader**: 0.15.7
**Minecraft Version**: 1.20.1

**Describe the bug**
Game is crashing on load with mod enabled. I am unfamiliar with reading crash logs, so if there is any help available for mine I would greatly appreciate it.

[crash-2024-03-31_19.08.28-client.txt](https://github.com/A5ho9999/MinecraftMods/files/14818630/crash-2024-03-31_19.08.28-client.txt)

**Comment by A5ho9999** [comment]
Thanks for the report, this appears to be an issue with CenteredPlants. Removing that mod should fix the issue. The mod is causing issues with multiple mods due to improper mixin usage

https://github.com/awesomebobby/CenteredPlants/issues
