### ISSUE TITLE
[Hopper The Hedgehog] - Duplication Issue

### ISSUE THREAD

**Issue by yannikkro** [A5ho9999/MinecraftMods#8]
**Hopper the Hedgehog**:
**1.4.0**:
**0.96.3**:
**1.20.4**:

**when the amount from hopper is higher than dispenser/Dropper is the dispenser/dropper invinite**

when you put a hopper into the dropper/dispenser and the dispenser is full its invinite

dispenser/dropper is infinite

![Base Profile Screenshot 2024 04 10 - 11 41 50 22](https://github.com/A5ho9999/MinecraftMods/assets/166605002/6182ae25-4a2f-4a98-bc15-0c7569479aa3)
![Base Profile Screenshot 2024 04 10 - 11 41 57 59](https://github.com/A5ho9999/MinecraftMods/assets/166605002/a982a3ca-409f-4f14-b112-a8fc9ad4e9a9)

**Comment by A5ho9999** [comment]
This issue will take a bit to resolve and will most likely take some major changes to fix as it's an issue with the whole hopper system.

**Comment by yannikkro** [comment]
Hello

Okay, thanks for the quick reply. Will I be notified when the problem has
been solved?



A5ho9999 ***@***.***> schrieb am Do., 11. Apr. 2024, 04:24:

**Comment by A5ho9999** [comment]
A new version has been released that should resolve this issue. Please let me know if you still encounter issues in this release.

For 1.20 - 1.20.1: https://modrinth.com/mod/hopper-the-hedgehog/version/2.0.0-1.20
For 1.20.2 - 1.20.4: https://modrinth.com/mod/hopper-the-hedgehog/version/2.0.0-1.20.2

**Comment by yannikkro** [comment]
Hello, first of all thank you for your quick solution. But I don't want to make you mad, but you swapped hopper input with the output. If you set input to 64, the whole stack disappears into a sorting system and the filter is gone. And for whatever reason, items now simply slide over the hopper without being picked up. For example, with a filter for cobblestone, the stone simply slides over without being picked up. But there is one positive: the dublication glitch is gone, thank you for that. Would it be possible for you to look at the other one too or maybe put the old one back without controlling the input output individually

**Comment by yannikkro** [comment]
I think I know what the problem is when you set the in and output to 64, the game lags from the MS and the items are bugged back and when you make all settings off than it works to try it yourself put a water stream on the floor with hopper below than make one hopper full and put 32 items in on one slot and make the other full with any items then throw 34 items into the stream

**Comment by A5ho9999** [comment]
It's not recommended to use the Mod with most auto-sorting systems as systems are designed for vanilla hopper usages. If you are using auto-sorters you can't use different input or outputs. Mainly the outputs now.

If you wish to use auto-sorters please see the Troubleshooting & Recommended usage on the [Mod Page](https://modrinth.com/mod/hopper-the-hedgehog)

The now implements performance changes much like that being added in 1.20.5. You will need to toggle this off if the Hoppers are picking up items too slow. 

The changes to hoppers are:
1. Enhances item transporting to reduce how often container are updated.
2. When Hoppers detect and item it will enter transfer cooldown to avoid spamming detections.
3. When a container is on a hopper, the Hopper will stop Item detection  and only accept input from the container.
4. When a full-cube block is on the hopper, the hopper will stop input functions, and only accept from other hoppers.

**Comment by yannikkro** [comment]
Yes, I know, I've read it, but with the previous version with the duplicating glitch everything works smoothly with the hoppers because everything is picked up and doesn't slide over the hopper

**Comment by A5ho9999** [comment]
As explained, this release contains performance changes affecting how hoppers work. Toggling this off in the config will result in normal hopper functions. The slow pick up is due to the hoppers not spamming scans for items above repeatedly

**Comment by yannikkro** [comment]
No I tried turn perfomance off it didnt work this is not the problem

**Comment by A5ho9999** [comment]
I have tested it with and without performance mode enabled, as well as with the mod completely removed. Everything is working as it should.

**Comment by yannikkro** [comment]
Okay, then I'll find another solution if you don't do it, but thanks anyway for your effort
